#!/bin/bash

log() {
  local stream=$1
  local color=$2
  local label=$3
  local msg=$4

  printf "\e[${color};1m[ %s ]\e[0m %s\n" "$label" "$msg" >&"$stream"
}

info() {
  $QUIET_MODE && return
  log 1 34 INFO "$1"
}

ok() {
  $QUIET_MODE && return
  printf '\e[1A\r\e[K'
  log 1 32 OK "$1"
}

warning() {
  log 2 33 WARNING "$1"
}

error() {
  log 2 31 ERROR "$1"
}

die() {
  error "$1" >&2
  exit 1
}

get_passphrase() {
  local pass1 pass2
  local first_attempt=true

  while true; do
    if ! first_attempt; then
      printf '\033[A\033[K\033[A\033[K\033[A\033[K'
    fi

    read -rs -p '[?] Enter LUKS passphrase: ' pass1
    echo
    read -rs -p '[?] Confirm passphrase: ' pass2
    echo

    first_attempt && first_attempt=false

    [[ -z $pass1 || ${#pass1} -gt 512 || $pass1 != $pass2 ]] && continue

    printf '%s' "$pass1"
    break
  done
}
